SELECT * FROM Students;
SELECT * FROM Courses;

SELECT S.NAME , C.COURSENAME FROM STUDENTS S INNER JOIN COURSES C ON S.CourseId = C.CourseId;

SELECT C.COURSENAME , COUNT(*) FROM STUDENTS S INNER JOIN COURSES C ON S.CourseId = C.CourseId 
GROUP BY C.CourseName;

SELECT * from Students where CourseId is NULL;

SELECT MAX(S.AGE) ,
       C.COURSENAME
FROM Students S
INNER JOIN Courses C
ON S.COURSEID = C.COURSEID
GROUP BY C.COURSENAME;